### ISSUE TITLE
Issue review 3

### ISSUE THREAD

**Issue by Miklet** [Nyweron/crud-table-app-reactjs#3]
1. TableKey -> Ten plik to prędzej nazwałbym TableHead jak coś :)

2.
https://github.com/Nyweron/crud-table-app-reactjs/blob/284e422a5cbfe2a611252ac521e4dbfec064aef7/src/components/table/TableKey.js#L10

Skoro to nie działa jak link, to po co go tutaj używać :) Używaj natywnego przycisku tylko nadaj mu style, żeby wyglądał jak nagłówek tabeli.

3. Dziwne też jest to, że w nagłówkach jest opcja usunięcia zamiast przy wierszu ;) To raczej wiersz chcesz usuwać.

4.
https://github.com/Nyweron/crud-table-app-reactjs/blob/284e422a5cbfe2a611252ac521e4dbfec064aef7/src/components/table/TableRow.js#L5

Ten prop jest wymagany, więc nie musisz weryfikować jego obecności :)

5.
https://github.com/Nyweron/crud-table-app-reactjs/blob/284e422a5cbfe2a611252ac521e4dbfec064aef7/src/components/table/TableRow.js#L6

Możesz też używać arrow function, więc zamiast `function (row) { ... }` możesz po prostu napisać `row => { ... }`

6.
https://github.com/Nyweron/crud-table-app-reactjs/blob/284e422a5cbfe2a611252ac521e4dbfec064aef7/src/components/table/TableRow.js#L21

Tutaj to wolałbym po prostu napisać `() => props.handleEdit(row.id)`, będzie czytelniej niż `.bind`.

7.
W implementacji Routera używasz baaaardzo starego api jeśli chodzi o context. Poczytaj to sobie, jest teraz o wiele prostsze: https://reactjs.org/docs/context.html 

8.
https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/container/TableContainer.js#L81

To bym wsadził do `.then` wyżej, bo nie wiesz czy się wywali czy nie.

9.
https://github.com/Nyweron/crud-table-app-reactjs/blob/284e422a5cbfe2a611252ac521e4dbfec064aef7/src/container/TableContainer.js#L96

Tutaj też nie panujesz nad flow, może się coś wywalić, a coś innego będzie w stanie aplikacji :)

10.
https://github.com/Nyweron/crud-table-app-reactjs/blob/284e422a5cbfe2a611252ac521e4dbfec064aef7/src/container/TableContainer.js#L159

Nie musisz wołać `setState` z każdą propertką bo możesz przekazać przecież obiekt, więc przekazujesz tyle ile chcesz. 

10a.
Jeśli chcesz wyliczać state na podstawie poprzedniego to lepiej jest pisać
```
setState(prevState => return {
  sort: !prevState.sort
});
```

`setState` działa tak, że nie ustawia stan od razu, a dodaje polecenie ustawienia stanu i odpali go być może od razu, a być może za chwilę. Mając to z tyłu głowy nie musisz opierać wartości o `this.state` bo ten stan może się zmienić przed wywołaniem konkretnym.

11.
https://github.com/Nyweron/crud-table-app-reactjs/blob/284e422a5cbfe2a611252ac521e4dbfec064aef7/src/container/TableContainer.js#L197

To jest bardzo stary sposób ustawiania ref i nie zaleca się jego używania. Są dwa rozwiązania obecnie, pierwsze to przekazanie tam funkcji i jawne przypisanie:
```
<div ref={node => { this.divRef = node; }} />
```
Druga opcja, jeszcze fajniejsza to deklaracja w klasie pola:
```
divRef = React.createRef();
```
a potem robisz:
```
<div ref={this.divRef} />
```

Na razie to są rzeczy, które rzuciły mi się w oczy :)

**Comment by Nyweron** [comment]
Pozwoliłem sobie troszkę z edytować Twoją wersje issue, dodając podpunkty, dzięki którym łatwiej będzie odnosić się do poszczególnych elementów :)

1. Ok kumam. 
https://github.com/Nyweron/crud-table-app-reactjs/pull/4/commits/ff6fc36365628e325dbd1edcf9e93290d1a59821
2. Racja, stare pozostałości :)
https://github.com/Nyweron/crud-table-app-reactjs/pull/4/commits/72938c647345b90b32254dc5d01a340e87147081
3. Tego punktu nie rozumiem. Chodzi Ci o to, że w wierszu {id | firstName | lastName | age | isActive | hobby | Remove | Edit} jest {Remove}?
4. Na początku kodowania, pamiętam, że bez tego miałem jakieś errory w poszczególnych sytuacjach.  Po testowałem, wychodzi na to, że ta niestabilność już nie występuję. Więc usunąłem warunek sprawdzający.
https://github.com/Nyweron/crud-table-app-reactjs/pull/4/commits/c52d574748ff1d38e43b69ec9b5c859f4ed1c153
5. Racja, w sumie nie dostrzegłem tego, nie jest to konieczne, ale jak już używam arrow, to wszędzie :)
https://github.com/Nyweron/crud-table-app-reactjs/pull/4/commits/c52d574748ff1d38e43b69ec9b5c859f4ed1c153
6. Nie znałem tej opcji, w sensie nie zdawałem sobie sprawy, że mogę to tak zapisać jak zaproponowałeś :)
https://github.com/Nyweron/crud-table-app-reactjs/pull/4/commits/2feb059ad7e4d81961a470d174733fe0f42203a8
7. Router obecnie za komentowałem bo obecnie go nie używam, ale dobrze wiedzieć, gdy nadejdzie jego czas z aktualizuję go 👍 
8. Dobra, teraz będę wiedział, aby takie elementy kodu pisać razem :)
https://github.com/Nyweron/crud-table-app-reactjs/pull/4/commits/1467d1e0a10cddd7cf878398b11d1f159ea8c4e4
9. Tak samo jako punkt 8
10. Do tego muszę jeszcze pomyśleć, bo nie wiem jak to ogarnąć ;p
10a. Super!, dobrze wiedzieć :)
https://github.com/Nyweron/crud-table-app-reactjs/pull/4/commits/150581cb2cda45cef97458e1de0830fad2084237
11. Również tak samo jak 10a.
https://github.com/Nyweron/crud-table-app-reactjs/pull/4/commits/97eab1fa57253495beb290e27e9153ed9d40953d

Dzięki za issue :D trochę oswoję temat i dam Ci sygnał na kolejny XD :D

**Comment by Miklet** [comment]
> 3\. Tego punktu nie rozumiem. Chodzi Ci o to, że w wierszu {id | firstName | lastName | age | isActive | hobby | Remove | Edit} jest {Remove}?

Chodzi mi o to, że wygląda (albo źle zrozumiałem kod) że w Twoich nagłówkach w tabeli poza samymi nagłówkami masz jeszcze Remove/Edit. Zmierzam do tego, że zazwyczaj jeśli masz takie opcje to dotyczą one wiersza w tabeli i to w nim powinny się znajdować np. na końcu wiersza w postaci ikon :)
