### ISSUE TITLE
Review part 2

### ISSUE THREAD

**Issue by Miklet** [Nyweron/crud-table-app-reactjs#7]
1. [Modale ](https://github.com/Nyweron/crud-table-app-reactjs/blob/3bb1556e09fa94670c5dab16b905480543f01210/src/components/modal/Modal.js#L10)polecam robić przy pomocy `React.createPortal` i lepiej jest zwracać `null` jeśli go aktualnie nie wyświetlasz, skoro nie musi być widoczny to można spokojnie go nie renderować.

2. Wolę [takie sprawdzenia](https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/components/table/TableHead.js#L5) robić w komponencie który używa tego komponentu. Dziwne to trochę, że mam komponent, który według nazwy coś renderuje, a jednak w pewnych chwilach nie zwraca nic :) 

3. Jeśli opierasz [nowy stan o poprzedni](https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/container/TableContainer.js#L67) to używaj formy `setState` z argumentem w postaci funkcji ;) Możesz w dokumentacji Reacta doczytać sobie, głównie chodzi o to, że `setState` jest asynchroniczne i możesz w `this.state` dostać stare/nieaktualne dane przez co Twój stan będzie niepoprawny.

4. Zdecydowanie ta [funkcja](https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/container/TableContainer.js#L125) wyglądała by lepiej gdyby zamiast tylu ifów były wywołania `setState` w staci: `this.setState({ stateProp: condition ? val1 : val2 })`. Takie mam odczucia.

5. Z jednej strony masz `show` [tutaj](https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/container/TableContainer.js#L167), a z drugiej w komponencie do którego przekazujesz. Czy nie można zostawić go w komponencie `TableContainer`? Przez to masz tą samą informacje i tu i tu niepotrzebnie :) Chyba, że te flagi są różne to ok, ale nadal nie powinno się kopiować propów do stanu. Jedynie w kilku przypadkach np. inicjalizacja stanu.

**Comment by Nyweron** [comment]
2. [coś takiego zrobiłem](https://github.com/Nyweron/crud-table-app-reactjs/pull/11/commits/f7dd71669b6bd3412f2c9fbfb79df87b8d535611)

**Comment by Nyweron** [comment]
2. [Coś takiego zrobiłem](https://github.com/Nyweron/crud-table-app-reactjs/pull/11/commits/f7dd71669b6bd3412f2c9fbfb79df87b8d535611), to miałeś na myśli?

**Comment by Nyweron** [comment]
Paweł czekam na poprawki :)

**Comment by Miklet** [comment]
Sprawa z Modalem jest nadal aktualna, sprawdź sobie `createPortal`.

[Tutaj](https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/components/table/PersonForm.js#L211) podzieliłbym na dwa osobne komponenty.

[Tutaj](https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/components/table/TableAdd.js#L39) i ogólnie zazwyczaj wszędzie lepiej jest kontrolować po prostu z komponentu nadrzędnego, bo w ten sposób dublujesz sobie logikę wyświetlania.

[main](https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/components/table/TableAdd.js#L49) sugeruje, że jest to główny element Twojej strony, chyba raczej tak nie jest :)

Pamiętaj, aby [nie kopiowac](https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/components/table/TableEdit.js#L12) do stanu wartości z propów. W 90% przypadków tego nie potrzebujesz, wystarczy wynieść coś do komponentu wyżej i kontrolować za pomocą propów.

[Tutaj[(https://github.com/Nyweron/crud-table-app-reactjs/blob/master/src/components/table/TableEdit.js#L52), dlaczego `Modal` jest nad `PersonForm`, a jednak `PersonForm` ma propa `hideModal`. Coś chyba nie jest do końca tak ;) 

Tą paginacje zostawię sobie na potem, sporo się tam dzieje :P

**Comment by Nyweron** [comment]
1. Jeszcze nad tym pracuje.

2. [Zrobione](https://github.com/Nyweron/crud-table-app-reactjs/commit/2720ae25c54ce2a3ea7a6e2a3d94c391e22d5817)

3. [Zrobione](https://github.com/Nyweron/crud-table-app-reactjs/commit/c83b4ac811ab84d0d03fe149a30788d41802ddf8)

4. [Zrobione](https://github.com/Nyweron/crud-table-app-reactjs/commit/1c612f1f899c1924165324b2d29f8deb0ceae838)

5. [Zrobione](https://github.com/Nyweron/crud-table-app-reactjs/commit/01eb4e4dee42067feccf13ba4b20f652353477fb)

6. Tutaj nie rozumiem :)
` <Modal show={this.state.show}>
          <PersonFormEdit
            submitEditForm={this.submitEditForm}
            hideModal={this.hideModal}
            data={this.props.row}
          />
   </Modal>`
Modal jest powiedzmy 'plakatem', na którym wyświetlane są informacje.  PersonFormEdit jest dzieckiem, a Modal rodzicem. Jeżeli dziecko wykonuje jakąś zmianę 'hideModal' to wysyła informację do rodzica 'słuchaj rodzic, zamykam modal, zmień show na false'. 

Ja tak sobie wyobraziłem to, że Modal mam być  wielokrotnego użytku, czyli mogę wrzucić cokolwioek chce do środka, co pozwala mi na tworzenie modalu :D, czyli okienka z konkretną informacją na pierwszym planie, a pozostałe plany są 'wyszarzane' :)

Jeżeli się nie zrozumieliśmy, to wyjaśnij proszę co masz na myśli :D
